// @ts-check
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { setupProject, git } from '../helpers/project.mjs'

const pick = (/** @type {RegExp} */ re) => ({ match: 'What do you want to publish?', answer: (/** @type {any} */ c) => re.test(c.label) })
const FINAL = pick(/^(final|finish) /)

/**
 * @param {import('../helpers/project.mjs').TestProject} p
 * @param {string} startAnswer
 * @param {string} version
 */
async function startRelease(p, startAnswer, version) {
  await p.cli('start', [{ match: 'What do you want to start?', answer: startAnswer }])
  await p.writeChangelog(`release/${version}`, version)
  return p.folder(`release/${version}`)
}

test('prereleases: numbering, npm tags, GitHub Pre-release; the branch stays', async (t) => {
  const p = await setupProject({ version: '1.0.0' })
  t.after(() => p.dispose())
  const folder = await startRelease(p, '1.0.0', '1.0.0')
  await p.cli('publish', [pick(/^beta/)], { cwd: folder })
  await p.cli('publish', [pick(/^beta/)], { cwd: folder })
  await p.cli('publish', [pick(/^rc/)], { cwd: folder })
  assert.deepEqual([...p.registry.store.keys()], ['1.0.0-beta.1', '1.0.0-beta.2', '1.0.0-rc.1'])
  assert.equal(p.registry.tags.beta, '1.0.0-beta.2')
  assert.equal(p.registry.tags.rc, '1.0.0-rc.1')
  assert.equal(p.registry.tags.latest, undefined, 'latest never moves on a prerelease')
  const rel = p.gh.releaseList.find((r) => r.tagName === '1.0.0-rc.1')
  assert.ok(rel?.prerelease)
  assert.ok(p.exists(folder))
  assert.equal(JSON.parse(await p.show('refs/heads/release/1.0.0', 'package.json')).version, '1.0.0', 'no commit for a prerelease')
  const pkg = p.registry.store.get('1.0.0-rc.1')
  assert.ok(pkg)
  await p.cli('publish', [FINAL], { cwd: folder })
  assert.ok(p.registry.store.has('1.0.0'))
  await git(p.work, ['pull', '--quiet', 'origin', 'main'])
  await git(p.work, ['switch', '--quiet', '-c', 'feature'])
  await p.commit(p.work, { 'src/index.js': 'export const x = 5\n' }, 'feat: five')
  await assert.rejects(
    p.cli('publish', [pick(/^alpha/), { match: 'Version of the prerelease', answer: '1.0.0' }]),
    /already released/,
  )
  await p.cli('publish', [pick(/^alpha/), { match: 'Version of the prerelease', answer: '1.1.0' }])
  assert.ok(p.registry.store.has('1.1.0-alpha.1'))
  assert.equal(p.registry.tags.alpha, '1.1.0-alpha.1')
})

test('a prerelease of a released version is refused; a failed prerelease gets the next number', async (t) => {
  const p = await setupProject({ version: '1.0.0' })
  t.after(() => p.dispose())
  const folder = await startRelease(p, '1.0.0', '1.0.0')
  await p.commit(folder, { FAIL: 'x' }, 'break')
  await assert.rejects(p.cli('publish', [pick(/^beta/)], { cwd: folder }), /failed/)
  assert.ok(await p.gh.tag('1.0.0-beta.1'), 'the failed tag stays')
  await p.commit(folder, { FAIL: null }, 'fix')
  await p.cli('publish', [pick(/^beta/)], { cwd: folder })
  assert.ok(p.registry.store.has('1.0.0-beta.2'))
  await p.cli('publish', [FINAL], { cwd: folder })
  await p.cli('start', [{ match: 'What do you want to start?', answer: 'patch' }])
  const other = await git(p.work, ['rev-parse', 'HEAD'])
  assert.ok(other)
})

test('requireTestedPrerelease: no final without an rc; the final is compared with the rc', async (t) => {
  const p = await setupProject({ version: '1.0.0', requireTestedPrerelease: true })
  t.after(() => p.dispose())
  const folder = await startRelease(p, '1.0.0', '1.0.0')
  await assert.rejects(p.cli('publish', [FINAL], { cwd: folder }), /no prerelease of 1.0.0 is released/)
  await p.cli('publish', [pick(/^rc/)], { cwd: folder })
  await p.cli('publish', [FINAL], { cwd: folder })
  assert.ok(p.registry.store.has('1.0.0'))
  assert.match((await p.gh.tag('1.0.0'))?.message ?? '', /candidate: 1\.0\.0-rc\.1/)

  const f2 = await startRelease(p, 'minor', '1.1.0')
  await p.cli('publish', [pick(/^rc/)], { cwd: f2 })
  await p.commit(f2, { 'src/index.js': 'export const x = 2\n' }, 'change after the rc')
  await assert.rejects(p.cli('publish', [FINAL], { cwd: f2 }), /package check|differs|nothing was published/)
  assert.equal(p.registry.store.has('1.1.0'), false)
  await p.cli('publish', [pick(/^rc/)], { cwd: f2 })
  await p.cli('publish', [FINAL], { cwd: f2 })
  assert.ok(p.registry.store.has('1.1.0'))
  assert.match((await p.gh.tag('1.1.0'))?.message ?? '', /candidate: 1\.1\.0-rc\.2/)
})

test('dev build: GitHub only, with the package attached; a name instead of the time', async (t) => {
  const p = await setupProject({ version: '1.0.0' })
  t.after(() => p.dispose())
  await git(p.work, ['switch', '--quiet', '-c', 'feature'])
  await p.commit(p.work, { 'src/index.js': 'export const x = 3\n' }, 'feat: x')
  await p.cli('publish', [pick(/^dev/), { match: 'Dev build', answer: '' }])
  const dev = p.gh.releaseList.find((r) => /^1\.0\.0-dev\.\d{14}$/.test(r.tagName))
  assert.ok(dev, 'a dev build named after the time')
  assert.ok(dev.prerelease)
  assert.equal(dev.assets.length, 1)
  assert.match(dev.assets[0].name, /^test-pkg-1\.0\.0-dev\.\d{14}\.tgz$/)
  assert.equal(p.registry.store.size, 0, 'nothing on npm')
  assert.match(p.lastUi?.text() ?? '', /"@test\/pkg": "https:\/\/github\.com\/test\/pkg\/releases\/download\//)
  await p.cli('publish', [pick(/^dev/), { match: 'Dev build', answer: 'new-filter' }])
  assert.ok(await p.gh.tag('1.0.0-dev.new-filter'))
  await assert.rejects(p.cli('publish', [pick(/^dev/), { match: 'Dev build', answer: 'new-filter' }]), /taken/)
})

test('hotfix of an older line: next patch from the tag, latest-X.Y, changelog pull request into main', async (t) => {
  const p = await setupProject({ version: '1.0.0' })
  t.after(() => p.dispose())
  const f1 = await startRelease(p, '1.0.0', '1.0.0')
  await p.cli('publish', [FINAL], { cwd: f1 })
  const f2 = await startRelease(p, 'minor', '1.1.0')
  await p.cli('publish', [FINAL], { cwd: f2 })
  await p.cli('start', [{ match: 'What do you want to start?', answer: '1.0.0 → 1.0.1' }])
  const hf = p.folder('hotfix/1.0.1')
  assert.ok(p.exists(hf))
  assert.equal(await git(hf, ['rev-parse', 'HEAD~1']), await p.sha('1.0.0^{commit}'), 'starts from the tag 1.0.0')
  await p.commit(hf, { 'src/index.js': 'export const x = 101\n' }, 'fix: x')
  await p.writeChangelog('hotfix/1.0.1', '1.0.1')
  await p.cli('publish', [FINAL], { cwd: hf })
  assert.ok(p.registry.store.has('1.0.1'))
  assert.equal(p.registry.tags['latest-1.0'], '1.0.1')
  assert.equal(p.registry.tags.latest, '1.1.0', 'latest stays')
  assert.equal(p.gh.releaseList.find((r) => r.id === p.gh.latestReleaseId)?.tagName, '1.1.0', 'Latest stays')
  assert.match(await p.show('main', 'doc/changelog/1.0.1.md'), /^1\.0\.1 — /)
  const index = await p.show('main', 'CHANGELOG.md')
  assert.ok(index.indexOf('[1.1.0]') < index.indexOf('[1.0.1]') && index.indexOf('[1.0.1]') < index.indexOf('[1.0.0]'), 'sorted by version')
  assert.equal(await p.show('main', 'src/index.js'), 'export const x = 1', 'the code in main is not touched')
  assert.equal(p.exists(hf), false)
  assert.equal(await p.gh.branchSha('hotfix/1.0.1'), null)
  assert.equal(await p.gh.branchSha('docs/changelog-1.0.1'), null)
  assert.match(p.lastUi?.text() ?? '', /patch release/)
})

test('a hotfix branch with main merged into it is refused before the tag', async (t) => {
  const p = await setupProject({ version: '1.0.0' })
  t.after(() => p.dispose())
  await p.cli('publish', [FINAL], { cwd: await startRelease(p, '1.0.0', '1.0.0') })
  await p.cli('publish', [FINAL], { cwd: await startRelease(p, 'minor', '1.1.0') })
  await p.cli('start', [{ match: 'What do you want to start?', answer: '1.0.0 → 1.0.1' }])
  const hf = p.folder('hotfix/1.0.1')
  await p.writeChangelog('hotfix/1.0.1', '1.0.1')
  await git(hf, ['fetch', '--quiet', 'origin', 'main'])
  await git(hf, ['merge', '--quiet', '--no-edit', 'FETCH_HEAD'])
  await git(hf, ['push', '--quiet', 'origin', 'HEAD:refs/heads/hotfix/1.0.1'])
  await assert.rejects(p.cli('publish', [pick(/^rc/)], { cwd: hf }), /newer line/)
  assert.equal(await p.gh.tag('1.0.1-rc.1'), null)
})

test('publish: "none": GitHub Releases only, prereleases counted as released, dev builds without a package', async (t) => {
  const p = await setupProject({ version: '0.0.1', publish: 'none' })
  t.after(() => p.dispose())
  const folder = await (async () => {
    await p.cli('start', [{ match: 'What do you want to start?', answer: 'custom' }, { match: 'Version', answer: '3.0.0' }])
    await p.writeChangelog('release/3.0.0', '3.0.0')
    return p.folder('release/3.0.0')
  })()
  await p.cli('publish', [pick(/^rc/)], { cwd: folder })
  assert.ok(p.gh.releaseList.find((r) => r.tagName === '3.0.0-rc.1')?.prerelease)
  await p.cli('publish', [FINAL], { cwd: folder })
  const rel = p.gh.releaseList.find((r) => r.tagName === '3.0.0')
  assert.ok(rel && !rel.draft)
  assert.equal(p.gh.latestReleaseId, rel.id)
  assert.equal(p.registry.store.size, 0)
  assert.equal(JSON.parse(await p.show('main', 'package.json')).version, '3.0.0')
  const run = p.gh.runList.find((r) => r.headBranch === '3.0.0' && !r.deleted)
  const publishJob = run.jobs.find((/** @type {any} */ j) => j.name === 'publish')
  assert.equal(publishJob.outputs['released-now'], 'true')
  assert.equal(publishJob.outputs.latest, 'true')
  assert.equal(publishJob.outputs.published, 'true')
  await git(p.work, ['pull', '--quiet', 'origin', 'main'])
  await git(p.work, ['switch', '--quiet', '-c', 'feature'])
  await p.commit(p.work, { 'src/index.js': 'export const x = 9\n' }, 'feat: y')
  await p.cli('publish', [pick(/^dev/), { match: 'Dev build', answer: 'try' }])
  const dev = p.gh.releaseList.find((r) => r.tagName === '3.0.0-dev.try')
  assert.ok(dev?.prerelease)
  assert.equal(dev.assets.length, 0)
})
